### ISSUE TITLE
step 4 in install instruction

### ISSUE THREAD

**Issue by hoangdzung** [bitsun/faiss-windows#3]
# Summary

# Platform

OS: Win 10

Faiss version: 

Faiss compilation options: 

Running on :
- [ ] CPU
- [ ] GPU

# Reproduction instructions

 
I've followed your instruction in read-me file. I've finished the first three steps, but in 4th step, I can't find any files with name "b2". Can you help me solve this problem? Maybe I did something wrong with boost

**Comment by bitsun** [comment]
I meant b2.exe, this can be found in the boost root directory

**Comment by hoangdzung** [comment]
I decided to move to Ubuntu instead of Windows. Maybe I will try this later. Thank you very much for your work.
